name = input()
counter = int(input())
weight = int(input())
money = int(input())
print('================Чек================')
print("Товар:" + f"{name:>29}")
print("Цена:" + "{:>30}".format(f'{weight}кг * {counter}руб/кг'))
print('Итого:' + "{:>29}".format(f'{weight * counter}руб'))
print('Внесено:' + "{:>27}".format(f'{money}руб'))
print("Сдача:" + "{:>29}".format(f'{money - weight * counter}руб'))
print('===================================')