name = input()
counter = int(input())
weight = int(input())
money = int(input())
print('Чек')
print(f'{name} - {weight}кг - {counter}руб/кг')
print(f'Итого: {weight * counter}руб')
print(f'Внесено: {money}руб')
print(f'Сдача: {money - weight * counter}руб')